name: Generate API Documentation

on:
  push:
    branches:
      - main

jobs:
  apidoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install apidoc

    - name: Generate API documentation
      run: npx apidoc -i src/ -o docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./docs  # Directory with your generated docs
      publish_branch: gh-pages  # Branch for GitHub Pages
